/* Textes des fléchettes. */
ajouterTextes({
fr:{
  "fl.name":"Fléchettes",
  "fl.tile.sub":"501 et 301, fin sur un double",
  "fl.mode.solo":"Individuel",
  "fl.mode.solo.sub":"Chacun pour soi",
  "fl.mode.team":"Équipes",
  "fl.mode.team.sub":"Score commun",
  "fl.depart":"Score de départ",
  "fl.depart.hint":"Fin obligatoire sur un double, en une seule manche.",
  "fl.players":"Joueurs",
  "fl.teams":"Équipes",
  "fl.per":"Joueurs par équipe",
  "fl.note":"{n} joueurs · {d} double out",
  "fl.note.team":"{n} équipes · {d} double out",
  "fl.playern":"Joueur {n}",
  "fl.teamn":"Équipe {n}",
  "fl.player.aria":"Nom du joueur {n}",
  "fl.team.aria":"Nom de l'équipe {n}",
  "fl.mate.aria":"Joueur {j} de l'équipe {n}",
  "fl.color.aria":"Couleur du joueur {n}",
  "fl.start":"{n} · double out",
  "fl.turn":"À {name}",
  "fl.turn.team":"À {team} · {name}",
  "fl.done":"Partie terminée",
  "fl.total":"Total",
  "fl.aim":"Visez, puis levez le doigt",
  "fl.miss":"Raté",
  "fl.cancel":"Annuler la fléchette",
  "fl.bust":"Bust · {name} revient à {n}",
  "fl.won":"{name} gagne sur {lib}",
  "fl.board.aria":"Cible : posez le doigt sur un segment, glissez pour ajuster, levez pour valider",
  "fl.sheet.empty":"Aucune fléchette lancée pour l'instant.",
  "fl.sheet.hint":"Touchez une fléchette pour la corriger : la partie est rejouée depuis elle.",
  "fl.col.volee":"Volée",
  "fl.col.left":"Reste",
  "fl.edit.title":"Correction · volée {v} · fléchette {n}",
  "fl.edit.delete":"Supprimer cette fléchette",
  "fl.fix.aria":"Corriger la fléchette {n}",
  "fl.done.volees":"Partie terminée en {n} volée",
  "fl.done.volees_p":"Partie terminée en {n} volées",
  "fl.checkout":"pour finir {n}",
  "fl.rank":"Classement",
  "fl.left":"Reste",
  "fl.avg":"Moy. 3 fl.",
  "fl.best":"Meilleure",
  "fl.busts":"Busts",
  "frules.count":"Comptage",
  "frules.single":"Simple : la valeur du secteur",
  "frules.double":"Double : l'anneau extérieur",
  "frules.triple":"Triple : l'anneau intérieur, T20 = 60",
  "frules.bull":"Demi-centre, vert",
  "frules.dbull":"Centre, rouge — compte comme un double",
  "frules.flow":"Déroulé",
  "frules.1a":"Chacun part de ",
  "frules.1b":"501 ou 301",
  "frules.1c":" et doit tomber à 0 pile avant les autres.",
  "frules.2a":"Une volée, ce sont ",
  "frules.2b":"trois fléchettes",
  "frules.2c":" : leur total est retiré du score. Une fléchette tombée ne compte pas.",
  "frules.3a":"La dernière fléchette doit être ",
  "frules.3b":"un double",
  "frules.3c":" ou le centre : s'il reste 32, il faut le double 16.",
  "frules.4a":"Passer sous 0, tomber à 1 ou finir sans double, c'est ",
  "frules.4b":"un bust",
  "frules.4c":" : le score revient à celui du début de la volée.",
  "frules.5a":"En équipes, les membres ",
  "frules.5b":"lancent à tour de rôle",
  "frules.5c":" et partagent un score."
},
en:{
  "fl.name":"Darts",
  "fl.tile.sub":"501 and 301, double out",
  "fl.mode.solo":"Individual",
  "fl.mode.solo.sub":"Each on their own",
  "fl.mode.team":"Teams",
  "fl.mode.team.sub":"Shared score",
  "fl.depart":"Starting score",
  "fl.depart.hint":"Finish on a double, in a single leg.",
  "fl.players":"Players",
  "fl.teams":"Teams",
  "fl.per":"Players per team",
  "fl.note":"{n} players · {d} double out",
  "fl.note.team":"{n} teams · {d} double out",
  "fl.playern":"Player {n}",
  "fl.teamn":"Team {n}",
  "fl.player.aria":"Name of player {n}",
  "fl.team.aria":"Name of team {n}",
  "fl.mate.aria":"Player {j} of team {n}",
  "fl.color.aria":"Colour of player {n}",
  "fl.start":"{n} · double out",
  "fl.turn":"{name} to throw",
  "fl.turn.team":"{team} · {name} to throw",
  "fl.done":"Game over",
  "fl.total":"Total",
  "fl.aim":"Aim, then lift your finger",
  "fl.miss":"Missed",
  "fl.cancel":"Undo dart",
  "fl.bust":"Bust · {name} back to {n}",
  "fl.won":"{name} wins on {lib}",
  "fl.board.aria":"Dartboard: touch a segment, slide to adjust, lift to confirm",
  "fl.sheet.empty":"No darts thrown yet.",
  "fl.sheet.hint":"Tap a dart to correct it: the game replays from there.",
  "fl.col.volee":"Visit",
  "fl.col.left":"Left",
  "fl.edit.title":"Correction · visit {v} · dart {n}",
  "fl.edit.delete":"Delete this dart",
  "fl.fix.aria":"Correct dart {n}",
  "fl.done.volees":"Game over in {n} visit",
  "fl.done.volees_p":"Game over in {n} visits",
  "fl.checkout":"to finish {n}",
  "fl.rank":"Standings",
  "fl.left":"Left",
  "fl.avg":"3-dart avg",
  "fl.best":"Best",
  "fl.busts":"Busts",
  "frules.count":"Scoring",
  "frules.single":"Single: the segment's number",
  "frules.double":"Double: the outer ring",
  "frules.triple":"Treble: the inner ring, T20 = 60",
  "frules.bull":"Outer bull, green",
  "frules.dbull":"Bullseye, red — counts as a double",
  "frules.flow":"How it goes",
  "frules.1a":"Everyone starts on ",
  "frules.1b":"501 or 301",
  "frules.1c":" and must reach exactly 0 before the others.",
  "frules.2a":"A visit is ",
  "frules.2b":"three darts",
  "frules.2c":": their total comes off the score. A dart that falls out does not count.",
  "frules.3a":"The last dart must be ",
  "frules.3b":"a double",
  "frules.3c":" or the bullseye: on 32, you need double 16.",
  "frules.4a":"Going below 0, landing on 1 or reaching 0 without a double is ",
  "frules.4b":"a bust",
  "frules.4c":": the score goes back to where the visit started.",
  "frules.5a":"In teams, members ",
  "frules.5b":"throw in turn",
  "frules.5c":" and share one score."
},
es:{
  "fl.name":"Dardos",
  "fl.tile.sub":"501 y 301, cierre con doble",
  "fl.mode.solo":"Individual",
  "fl.mode.solo.sub":"Cada uno por su cuenta",
  "fl.mode.team":"Equipos",
  "fl.mode.team.sub":"Puntuación común",
  "fl.depart":"Puntuación inicial",
  "fl.depart.hint":"Cierre obligatorio con doble, en una sola manga.",
  "fl.players":"Jugadores",
  "fl.teams":"Equipos",
  "fl.per":"Jugadores por equipo",
  "fl.note":"{n} jugadores · {d} doble salida",
  "fl.note.team":"{n} equipos · {d} doble salida",
  "fl.playern":"Jugador {n}",
  "fl.teamn":"Equipo {n}",
  "fl.player.aria":"Nombre del jugador {n}",
  "fl.team.aria":"Nombre del equipo {n}",
  "fl.mate.aria":"Jugador {j} del equipo {n}",
  "fl.color.aria":"Color del jugador {n}",
  "fl.start":"{n} · doble salida",
  "fl.turn":"Turno de {name}",
  "fl.turn.team":"Turno de {team} · {name}",
  "fl.done":"Partida terminada",
  "fl.total":"Total",
  "fl.aim":"Apunta y levanta el dedo",
  "fl.miss":"Fallo",
  "fl.cancel":"Anular el dardo",
  "fl.bust":"Bust · {name} vuelve a {n}",
  "fl.won":"{name} gana con {lib}",
  "fl.board.aria":"Diana: toca un sector, desliza para ajustar, levanta para validar",
  "fl.sheet.empty":"Aún no se ha lanzado ningún dardo.",
  "fl.sheet.hint":"Toca un dardo para corregirlo: la partida se recalcula desde ahí.",
  "fl.col.volee":"Tirada",
  "fl.col.left":"Quedan",
  "fl.edit.title":"Corrección · tirada {v} · dardo {n}",
  "fl.edit.delete":"Eliminar este dardo",
  "fl.fix.aria":"Corregir el dardo {n}",
  "fl.done.volees":"Partida terminada en {n} tirada",
  "fl.done.volees_p":"Partida terminada en {n} tiradas",
  "fl.checkout":"para cerrar {n}",
  "fl.rank":"Clasificación",
  "fl.left":"Quedan",
  "fl.avg":"Media 3 d.",
  "fl.best":"Mejor",
  "fl.busts":"Busts",
  "frules.count":"Puntuación",
  "frules.single":"Simple: el número del sector",
  "frules.double":"Doble: el anillo exterior",
  "frules.triple":"Triple: el anillo interior, T20 = 60",
  "frules.bull":"Diana exterior, verde",
  "frules.dbull":"Diana central, roja — cuenta como doble",
  "frules.flow":"Desarrollo",
  "frules.1a":"Todos empiezan en ",
  "frules.1b":"501 o 301",
  "frules.1c":" y deben llegar a 0 justo antes que los demás.",
  "frules.2a":"Una tirada son ",
  "frules.2b":"tres dardos",
  "frules.2c":": su total se resta de la puntuación. Un dardo que cae no cuenta.",
  "frules.3a":"El último dardo debe ser ",
  "frules.3b":"un doble",
  "frules.3c":" o la diana central: con 32, hace falta el doble 16.",
  "frules.4a":"Bajar de 0, quedarse en 1 o llegar a 0 sin doble es ",
  "frules.4b":"un bust",
  "frules.4c":": la puntuación vuelve a la del inicio de la tirada.",
  "frules.5a":"En equipos, los miembros ",
  "frules.5b":"lanzan por turnos",
  "frules.5c":" y comparten la puntuación."
}
});
