/* Textes du palet breton. */
ajouterTextes({
fr:{
  "games.palet.sub":"Sur planche, simple et double",
  "palet.name":"Palet breton",
  "setup.palets":"Palets par joueur",
  "game.palets":"{n} palets par équipe",
  "game.perpalet":"1 pt par palet",
  "game.void":"Manche nulle",
  "game.add.pt":"Ajouter un point",
  "game.rm.pt":"Retirer un point",
  "prules.title":"Le palet breton",
  "prules.count":"Comptage",
  "prules.pt":"par palet mieux placé que le meilleur adverse",
  "prules.flow":"Déroulé",
  "prules.1a":"L'équipe qui a marqué pose le ",
  "prules.1b":"maître",
  "prules.1c":" sur la planche et lance en premier.",
  "prules.2a":"Elle a ",
  "prules.2b":"trois essais",
  "prules.2c":" pour l'y placer ; sans succès, l'adversaire tente à son tour, trois essais aussi.",
  "prules.3a":"L'équipe qui n'a pas le point relance ",
  "prules.3b":"jusqu'à le reprendre",
  "prules.3c":" ou épuiser ses palets.",
  "prules.4a":"Seule l'équipe la plus proche marque : ",
  "prules.4b":"1 point par palet",
  "prules.4c":" mieux placé que le meilleur adverse.",
  "prules.5a":"Un palet tombé de la planche ",
  "prules.5b":"ne compte pas",
  "prules.5c":".",
  "prules.6a":"Si le maître quitte la planche, la manche est ",
  "prules.6b":"nulle",
  "prules.6c":" et se rejoue.",
  "over.avg":"Moyenne par manche",
  "setup.palet.hint":"La partie se joue en 12 points, la belle en 15.",
  "game.master":"Maître",
  "game.missed":"Manqué",
  "game.missed.aria":"Maître manqué en trois essais : passer le lancer à {name}"
},
en:{
  "games.palet.sub":"On the board, singles and doubles",
  "palet.name":"Breton palet",
  "setup.palets":"Palets per player",
  "game.palets":"{n} palets per team",
  "game.perpalet":"1 pt per palet",
  "game.void":"Void frame",
  "game.add.pt":"Add a point",
  "game.rm.pt":"Remove a point",
  "prules.title":"Breton palet",
  "prules.count":"Scoring",
  "prules.pt":"per palet closer than the opponent's best",
  "prules.flow":"How it goes",
  "prules.1a":"The team that scored sets the ",
  "prules.1b":"master",
  "prules.1c":" on the board and throws first.",
  "prules.2a":"It gets ",
  "prules.2b":"three attempts",
  "prules.2c":" to land it; failing that, the opponent tries, also with three.",
  "prules.3a":"The team without the point keeps throwing ",
  "prules.3b":"until it takes it back",
  "prules.3c":" or runs out of palets.",
  "prules.4a":"Only the closest team scores: ",
  "prules.4b":"1 point per palet",
  "prules.4c":" closer than the opponent's best.",
  "prules.5a":"A palet that falls off the board ",
  "prules.5b":"does not count",
  "prules.5c":".",
  "prules.6a":"If the master leaves the board, the frame is ",
  "prules.6b":"void",
  "prules.6c":" and is replayed.",
  "over.avg":"Average per frame",
  "setup.palet.hint":"A game is played to 12 points, the decider to 15.",
  "game.master":"Master",
  "game.missed":"Missed",
  "game.missed.aria":"Master missed in three attempts: pass the throw to {name}"
},
es:{
  "games.palet.sub":"Sobre tabla, individual y dobles",
  "palet.name":"Palet bretón",
  "setup.palets":"Paletes por jugador",
  "game.palets":"{n} paletes por equipo",
  "game.perpalet":"1 pt por palete",
  "game.void":"Ronda nula",
  "game.add.pt":"Añadir un punto",
  "game.rm.pt":"Quitar un punto",
  "prules.title":"El palet bretón",
  "prules.count":"Puntuación",
  "prules.pt":"por palete mejor colocado que el mejor rival",
  "prules.flow":"Desarrollo",
  "prules.1a":"El equipo que puntuó coloca el ",
  "prules.1b":"maestro",
  "prules.1c":" sobre la tabla y lanza primero.",
  "prules.2a":"Dispone de ",
  "prules.2b":"tres intentos",
  "prules.2c":" para colocarlo; si falla, lo intenta el rival, también con tres.",
  "prules.3a":"El equipo sin el punto vuelve a lanzar ",
  "prules.3b":"hasta recuperarlo",
  "prules.3c":" o agotar sus paletes.",
  "prules.4a":"Solo puntúa el equipo más cercano: ",
  "prules.4b":"1 punto por palete",
  "prules.4c":" mejor colocado que el mejor rival.",
  "prules.5a":"Un palete caído de la tabla ",
  "prules.5b":"no cuenta",
  "prules.5c":".",
  "prules.6a":"Si el maestro sale de la tabla, la ronda es ",
  "prules.6b":"nula",
  "prules.6c":" y se repite.",
  "over.avg":"Promedio por ronda",
  "setup.palet.hint":"La partida se juega a 12 puntos, la bella a 15.",
  "game.master":"Maestro",
  "game.missed":"Fallado",
  "game.missed.aria":"Maestro fallado en tres intentos: pasar el lanzamiento a {name}"
}
});
