/* Textes du Bibock. Le règlement dit « mène » : l'application dit manche. */
ajouterTextes({
fr:{
  "bi.name":"Bibock",
  "bi.tile.sub":"16 points ou élimination",
  "bi.per":"Joueurs par équipe",
  "bi.add":"Un joueur de plus par équipe", "bi.remove":"Un joueur de moins par équipe",
  "bi.note":"{n} contre {n} · 4 Bocks chacune",
  "bi.cible":"Score à atteindre",
  "bi.cible.hint":"16 points, ou 9 pour la variante express.",
  "bi.team.aria":"Nom de l'équipe {n}",
  "bi.color.aria":"Couleur de l'équipe {n}",
  "bi.mate.aria":"Joueur {j} de l'équipe {n}",
  "bi.col.pp":"Proches ×1", "bi.col.pm":"Maître ×5", "bi.col.bocks":"Bocks",
  "bi.rec":"Bocks récupérés en fin de manche",
  "bi.bocks":"{n} Bock", "bi.bocks_p":"{n} Bocks",
  "bi.rm.pp":"Un Bock proche de moins pour {name}", "bi.add.pp":"Un Bock proche de plus pour {name}",
  "bi.rm.pm":"Un Bock sur le Maître de moins pour {name}", "bi.add.pm":"Un Bock sur le Maître de plus pour {name}",
  "bi.rm.bk":"Un Bock récupéré de moins pour {name}", "bi.add.bk":"Un Bock récupéré de plus pour {name}",
  "bi.done":"Partie terminée",
  "bi.sheet.hint":"Touchez une manche pour corriger ses points ou ses Bocks. La partie est recalculée.",
  "bi.elim.note":"Par élimination : {name} n'a plus de Bock.",
  "bi.stat.maitre":"Sur le Maître", "bi.stat.bocks":"Bocks en fin de partie",
  "birules.count":"Comptage",
  "birules.pt":"Par Bock plus proche du Maître que le meilleur adverse",
  "birules.maitre":"Par Bock à cheval sur le Maître",
  "birules.groupe":"Un groupe compte en entier : 3 Bocks empilés, 3 points",
  "birules.flow":"Déroulé",
  "birules.1a":"Deux équipes de 1 à 4 joueurs, à 6 ou 8 mètres, le Maître au milieu. Chacune part avec ",
  "birules.1b":"4 Bocks",
  "birules.1c":" : c'est la face visible qui dit à qui appartient un Bock.",
  "birules.2a":"Les équipes lancent ",
  "birules.2b":"à tour de rôle",
  "birules.2c":" jusqu'au dernier Bock. Seule l'équipe la plus proche du Maître marque.",
  "birules.3a":"Un Bock recouvert est ",
  "birules.3b":"mangé",
  "birules.3c":" : le Bock du dessus impose sa couleur au groupe. Resté sur la tranche, il est neutre et ne compte pas.",
  "birules.4a":"En fin de manche, chaque équipe ",
  "birules.4b":"récupère les Bocks de sa couleur",
  "birules.4c":". Celle qui en a le plus commence la suivante, puis celle qui a le plus de points.",
  "birules.5a":"On gagne à ",
  "birules.5b":"16 points ou plus",
  "birules.5c":" — 9 en express —, ou en prenant tous les Bocks : l'équipe qui n'en a plus est éliminée.",
  "birules.6a":"À distance égale, ou avec un Bock de chaque équipe sur le Maître, ",
  "birules.6b":"la manche est nulle",
  "birules.6c":"."
},
en:{
  "bi.name":"Bibock",
  "bi.tile.sub":"16 points or knockout",
  "bi.per":"Players per team",
  "bi.add":"One more player per team", "bi.remove":"One fewer player per team",
  "bi.note":"{n} vs {n} · 4 Bocks each",
  "bi.cible":"Winning score",
  "bi.cible.hint":"16 points, or 9 for the express variant.",
  "bi.team.aria":"Name of team {n}",
  "bi.color.aria":"Colour of team {n}",
  "bi.mate.aria":"Player {j} of team {n}",
  "bi.col.pp":"Closest ×1", "bi.col.pm":"Master ×5", "bi.col.bocks":"Bocks",
  "bi.rec":"Bocks recovered at the end of the frame",
  "bi.bocks":"{n} Bock", "bi.bocks_p":"{n} Bocks",
  "bi.rm.pp":"One fewer closest Bock for {name}", "bi.add.pp":"One more closest Bock for {name}",
  "bi.rm.pm":"One fewer Bock on the Master for {name}", "bi.add.pm":"One more Bock on the Master for {name}",
  "bi.rm.bk":"One fewer Bock recovered by {name}", "bi.add.bk":"One more Bock recovered by {name}",
  "bi.done":"Game over",
  "bi.sheet.hint":"Tap a frame to correct its points or Bocks. The game is recalculated.",
  "bi.elim.note":"By knockout: {name} has no Bocks left.",
  "bi.stat.maitre":"On the Master", "bi.stat.bocks":"Bocks at the end",
  "birules.count":"Scoring",
  "birules.pt":"Per Bock closer to the Master than the opponents' best",
  "birules.maitre":"Per Bock resting on the Master",
  "birules.groupe":"A stack counts in full: 3 stacked Bocks, 3 points",
  "birules.flow":"How it goes",
  "birules.1a":"Two teams of 1 to 4 players, 6 to 8 metres apart, the Master in the middle. Each starts with ",
  "birules.1b":"4 Bocks",
  "birules.1c":": the face showing decides which team a Bock belongs to.",
  "birules.2a":"Teams throw ",
  "birules.2b":"in turn",
  "birules.2c":" until the last Bock. Only the team closest to the Master scores.",
  "birules.3a":"A covered Bock is ",
  "birules.3b":"eaten",
  "birules.3c":": the Bock on top gives its colour to the whole stack. One left standing on its edge is neutral and does not count.",
  "birules.4a":"At the end of a frame, each team ",
  "birules.4b":"takes back the Bocks showing its colour",
  "birules.4c":". The team with the most starts the next one, then the one with more points.",
  "birules.5a":"You win at ",
  "birules.5b":"16 points or more",
  "birules.5c":" — 9 in express — or by taking every Bock: the team left with none is knocked out.",
  "birules.6a":"If two Bocks are equally close, or each team has one on the Master, ",
  "birules.6b":"the frame is void",
  "birules.6c":"."
},
es:{
  "bi.name":"Bibock",
  "bi.tile.sub":"16 puntos o eliminación",
  "bi.per":"Jugadores por equipo",
  "bi.add":"Un jugador más por equipo", "bi.remove":"Un jugador menos por equipo",
  "bi.note":"{n} contra {n} · 4 Bocks cada uno",
  "bi.cible":"Puntuación objetivo",
  "bi.cible.hint":"16 puntos, o 9 para la variante exprés.",
  "bi.team.aria":"Nombre del equipo {n}",
  "bi.color.aria":"Color del equipo {n}",
  "bi.mate.aria":"Jugador {j} del equipo {n}",
  "bi.col.pp":"Cerca ×1", "bi.col.pm":"Maestro ×5", "bi.col.bocks":"Bocks",
  "bi.rec":"Bocks recuperados al final de la ronda",
  "bi.bocks":"{n} Bock", "bi.bocks_p":"{n} Bocks",
  "bi.rm.pp":"Un Bock cercano menos para {name}", "bi.add.pp":"Un Bock cercano más para {name}",
  "bi.rm.pm":"Un Bock sobre el Maestro menos para {name}", "bi.add.pm":"Un Bock sobre el Maestro más para {name}",
  "bi.rm.bk":"Un Bock recuperado menos para {name}", "bi.add.bk":"Un Bock recuperado más para {name}",
  "bi.done":"Partida terminada",
  "bi.sheet.hint":"Toca una ronda para corregir sus puntos o sus Bocks. La partida se recalcula.",
  "bi.elim.note":"Por eliminación: {name} ya no tiene Bocks.",
  "bi.stat.maitre":"Sobre el Maestro", "bi.stat.bocks":"Bocks al final",
  "birules.count":"Puntuación",
  "birules.pt":"Por Bock más cerca del Maestro que el mejor rival",
  "birules.maitre":"Por Bock encima del Maestro",
  "birules.groupe":"Un grupo cuenta entero: 3 Bocks apilados, 3 puntos",
  "birules.flow":"Desarrollo",
  "birules.1a":"Dos equipos de 1 a 4 jugadores, a 6 u 8 metros, con el Maestro en medio. Cada uno empieza con ",
  "birules.1b":"4 Bocks",
  "birules.1c":": la cara visible dice a quién pertenece un Bock.",
  "birules.2a":"Los equipos lanzan ",
  "birules.2b":"por turnos",
  "birules.2c":" hasta el último Bock. Solo puntúa el equipo más cercano al Maestro.",
  "birules.3a":"Un Bock cubierto queda ",
  "birules.3b":"comido",
  "birules.3c":": el de arriba impone su color a todo el grupo. Si queda de canto, es neutro y no cuenta.",
  "birules.4a":"Al final de la ronda, cada equipo ",
  "birules.4b":"recupera los Bocks de su color",
  "birules.4c":". Empieza la siguiente el que tiene más, y si no, el que tiene más puntos.",
  "birules.5a":"Se gana con ",
  "birules.5b":"16 puntos o más",
  "birules.5c":" — 9 en exprés — o quedándose con todos los Bocks: el equipo sin Bocks queda eliminado.",
  "birules.6a":"Con dos Bocks a igual distancia, o uno de cada equipo sobre el Maestro, ",
  "birules.6b":"la ronda es nula",
  "birules.6c":"."
}
});
