/* Textes du yams. */
ajouterTextes({
fr:{
  "ya.name":"Yams",
  "ya.tile.sub":"5 dés, 13 cases à remplir",
  "ya.players":"Joueurs",
  "ya.add":"Ajouter un joueur", "ya.remove":"Retirer un joueur",
  "ya.note":"{n} joueur · 13 tours", "ya.note_p":"{n} joueurs · 13 tours",
  "ya.playern":"Joueur {n}",
  "ya.player.aria":"Nom du joueur {n}",
  "ya.color.aria":"Couleur du joueur {n}",
  "ya.turn":"À {name}",
  "ya.tour":"Tour {n} / 13",
  "ya.done":"Partie terminée",
  "ya.dice.count":"Dés · {n} / 5",
  "ya.clear":"Effacer",
  "ya.die.add":"Ajouter un dé {n}",
  "ya.die.remove":"Retirer le dé {n}",
  "ya.upper":"Haut", "ya.lower":"Bas",
  "ya.subtotal":"Sous-total", "ya.bonus":"Bonus", "ya.total":"Total",
  "ya.c.1":"As", "ya.c.2":"Deux", "ya.c.3":"Trois", "ya.c.4":"Quatre", "ya.c.5":"Cinq", "ya.c.6":"Six",
  "ya.c.brelan":"Brelan", "ya.c.carre":"Carré", "ya.c.full":"Full",
  "ya.c.psuite":"Petite suite", "ya.c.gsuite":"Grande suite", "ya.c.yams":"Yams", "ya.c.chance":"Chance",
  "ya.enter":"Saisissez les 5 dés",
  "ya.pick":"Choisissez une case",
  "ya.write":"Inscrire {n} · {case}",
  "ya.cross":"Barrer {case} · 0",
  "ya.sheet":"Fiche de marque",
  "ya.sheet.empty":"Aucun tour joué pour l'instant.",
  "ya.sheet.hint":"Touchez une case remplie pour corriger ses dés ou la changer de case.",
  "ya.fix.aria":"Corriger {case} de {name}",
  "ya.undo":"Annuler le dernier tour",
  "ya.edit.title":"Correction · {name} · tour {n}",
  "ya.edit.case":"Case",
  "ya.over.eyebrow":"Partie terminée · {n} tours",
  "ya.tie":"Égalité",
  "ya.solo":"Partie de {name}",
  "ya.points":"points",
  "ya.record":"Record du palmarès",
  "ya.rank":"Classement",
  "ya.again":"Rejouer",
  "ya.records":"Meilleurs scores",
  "yrules.upper":"Le haut",
  "yrules.upper.sum":"As à Six : la somme des dés de ce chiffre",
  "yrules.bonus":"Bonus dès que le haut atteint 63 points",
  "yrules.lower":"Le bas",
  "yrules.brelan":"Brelan · 3 dés identiques au moins, somme des 5 dés",
  "yrules.carre":"Carré · 4 dés identiques au moins, somme des 5 dés",
  "yrules.full":"Full · 3 dés d'une valeur et 2 d'une autre",
  "yrules.psuite":"Petite suite · 4 dés qui se suivent",
  "yrules.gsuite":"Grande suite · 5 dés qui se suivent",
  "yrules.yams":"Yams · 5 dés identiques",
  "yrules.chance":"Chance · sans condition, somme des 5 dés",
  "yrules.flow":"Déroulé",
  "yrules.1a":"Chacun joue ",
  "yrules.1b":"13 tours",
  "yrules.1c":", un par case de sa fiche de marque.",
  "yrules.2a":"Un tour, c'est ",
  "yrules.2b":"3 lancers au plus",
  "yrules.2c":" : on garde des dés, on relance les autres, et on peut s'arrêter avant.",
  "yrules.3a":"En fin de tour, il faut ",
  "yrules.3b":"remplir une case libre",
  "yrules.3c":". Si les dés n'y correspondent pas, elle vaut 0 : elle est barrée.",
  "yrules.4a":"La partie finit quand ",
  "yrules.4b":"toutes les fiches sont pleines",
  "yrules.4c":". Le total additionne le haut, le bonus et le bas.",
  "yrules.5a":"On lance ",
  "yrules.5b":"de vrais dés",
  "yrules.5c":" : saisissez les 5 valeurs, choisissez la case, l'application compte."
},
en:{
  "ya.name":"Yams",
  "ya.tile.sub":"5 dice, 13 boxes to fill",
  "ya.players":"Players",
  "ya.add":"Add a player", "ya.remove":"Remove a player",
  "ya.note":"{n} player · 13 turns", "ya.note_p":"{n} players · 13 turns",
  "ya.playern":"Player {n}",
  "ya.player.aria":"Name of player {n}",
  "ya.color.aria":"Colour of player {n}",
  "ya.turn":"{name} to play",
  "ya.tour":"Turn {n} / 13",
  "ya.done":"Game over",
  "ya.dice.count":"Dice · {n} / 5",
  "ya.clear":"Clear",
  "ya.die.add":"Add a {n}",
  "ya.die.remove":"Remove the {n}",
  "ya.upper":"Upper", "ya.lower":"Lower",
  "ya.subtotal":"Subtotal", "ya.bonus":"Bonus", "ya.total":"Total",
  "ya.c.1":"Aces", "ya.c.2":"Twos", "ya.c.3":"Threes", "ya.c.4":"Fours", "ya.c.5":"Fives", "ya.c.6":"Sixes",
  "ya.c.brelan":"3 of a kind", "ya.c.carre":"4 of a kind", "ya.c.full":"Full house",
  "ya.c.psuite":"Sm. straight", "ya.c.gsuite":"Lg. straight", "ya.c.yams":"Yams", "ya.c.chance":"Chance",
  "ya.enter":"Enter the 5 dice",
  "ya.pick":"Pick a box",
  "ya.write":"Score {n} · {case}",
  "ya.cross":"Scratch {case} · 0",
  "ya.sheet":"Score card",
  "ya.sheet.empty":"No turns played yet.",
  "ya.sheet.hint":"Tap a filled box to correct its dice or move it to another box.",
  "ya.fix.aria":"Correct {case} for {name}",
  "ya.undo":"Undo last turn",
  "ya.edit.title":"Correction · {name} · turn {n}",
  "ya.edit.case":"Box",
  "ya.over.eyebrow":"Game over · {n} turns",
  "ya.tie":"It's a tie",
  "ya.solo":"{name}'s game",
  "ya.points":"points",
  "ya.record":"New record",
  "ya.rank":"Standings",
  "ya.again":"Play again",
  "ya.records":"High scores",
  "yrules.upper":"Upper section",
  "yrules.upper.sum":"Aces to Sixes: the sum of the dice showing that number",
  "yrules.bonus":"Bonus once the upper section reaches 63",
  "yrules.lower":"Lower section",
  "yrules.brelan":"Three of a kind · at least 3 matching dice, sum of all 5",
  "yrules.carre":"Four of a kind · at least 4 matching dice, sum of all 5",
  "yrules.full":"Full house · 3 of one value and 2 of another",
  "yrules.psuite":"Small straight · 4 dice in a row",
  "yrules.gsuite":"Large straight · 5 dice in a row",
  "yrules.yams":"Yams · 5 matching dice",
  "yrules.chance":"Chance · no condition, sum of all 5",
  "yrules.flow":"How it goes",
  "yrules.1a":"Everyone plays ",
  "yrules.1b":"13 turns",
  "yrules.1c":", one for each box on their score card.",
  "yrules.2a":"A turn is ",
  "yrules.2b":"up to 3 rolls",
  "yrules.2c":": keep some dice, reroll the others, and stop early if you like.",
  "yrules.3a":"At the end of a turn you must ",
  "yrules.3b":"fill an empty box",
  "yrules.3c":". If the dice don't meet its condition, it scores 0 and is scratched.",
  "yrules.4a":"The game ends when ",
  "yrules.4b":"every score card is full",
  "yrules.4c":". The total adds the upper section, the bonus and the lower section.",
  "yrules.5a":"You roll ",
  "yrules.5b":"real dice",
  "yrules.5c":": enter the 5 values, pick the box, and the app does the maths."
},
es:{
  "ya.name":"Yams",
  "ya.tile.sub":"5 dados, 13 casillas por llenar",
  "ya.players":"Jugadores",
  "ya.add":"Añadir un jugador", "ya.remove":"Quitar un jugador",
  "ya.note":"{n} jugador · 13 turnos", "ya.note_p":"{n} jugadores · 13 turnos",
  "ya.playern":"Jugador {n}",
  "ya.player.aria":"Nombre del jugador {n}",
  "ya.color.aria":"Color del jugador {n}",
  "ya.turn":"Turno de {name}",
  "ya.tour":"Turno {n} / 13",
  "ya.done":"Partida terminada",
  "ya.dice.count":"Dados · {n} / 5",
  "ya.clear":"Borrar",
  "ya.die.add":"Añadir un {n}",
  "ya.die.remove":"Quitar el {n}",
  "ya.upper":"Arriba", "ya.lower":"Abajo",
  "ya.subtotal":"Subtotal", "ya.bonus":"Bonus", "ya.total":"Total",
  "ya.c.1":"Unos", "ya.c.2":"Doses", "ya.c.3":"Treses", "ya.c.4":"Cuatros", "ya.c.5":"Cincos", "ya.c.6":"Seises",
  "ya.c.brelan":"Trío", "ya.c.carre":"Póker", "ya.c.full":"Full",
  "ya.c.psuite":"Esc. menor", "ya.c.gsuite":"Esc. mayor", "ya.c.yams":"Yams", "ya.c.chance":"Suerte",
  "ya.enter":"Introduce los 5 dados",
  "ya.pick":"Elige una casilla",
  "ya.write":"Anotar {n} · {case}",
  "ya.cross":"Tachar {case} · 0",
  "ya.sheet":"Hoja de puntos",
  "ya.sheet.empty":"Aún no se ha jugado ningún turno.",
  "ya.sheet.hint":"Toca una casilla llena para corregir sus dados o cambiarla de casilla.",
  "ya.fix.aria":"Corregir {case} de {name}",
  "ya.undo":"Anular el último turno",
  "ya.edit.title":"Corrección · {name} · turno {n}",
  "ya.edit.case":"Casilla",
  "ya.over.eyebrow":"Partida terminada · {n} turnos",
  "ya.tie":"Empate",
  "ya.solo":"Partida de {name}",
  "ya.points":"puntos",
  "ya.record":"Récord del historial",
  "ya.rank":"Clasificación",
  "ya.again":"Volver a jugar",
  "ya.records":"Mejores puntuaciones",
  "yrules.upper":"Arriba",
  "yrules.upper.sum":"Unos a Seises: la suma de los dados de ese número",
  "yrules.bonus":"Bonus en cuanto la parte de arriba llega a 63",
  "yrules.lower":"Abajo",
  "yrules.brelan":"Trío · al menos 3 dados iguales, suma de los 5",
  "yrules.carre":"Póker · al menos 4 dados iguales, suma de los 5",
  "yrules.full":"Full · 3 dados de un valor y 2 de otro",
  "yrules.psuite":"Escalera menor · 4 dados seguidos",
  "yrules.gsuite":"Escalera mayor · 5 dados seguidos",
  "yrules.yams":"Yams · 5 dados iguales",
  "yrules.chance":"Suerte · sin condición, suma de los 5",
  "yrules.flow":"Desarrollo",
  "yrules.1a":"Cada uno juega ",
  "yrules.1b":"13 turnos",
  "yrules.1c":", uno por casilla de su hoja de puntos.",
  "yrules.2a":"Un turno son ",
  "yrules.2b":"3 tiradas como máximo",
  "yrules.2c":": se guardan dados, se relanzan los demás, y se puede parar antes.",
  "yrules.3a":"Al final del turno hay que ",
  "yrules.3b":"llenar una casilla libre",
  "yrules.3c":". Si los dados no cumplen su condición, vale 0: queda tachada.",
  "yrules.4a":"La partida termina cuando ",
  "yrules.4b":"todas las hojas están llenas",
  "yrules.4c":". El total suma arriba, el bonus y abajo.",
  "yrules.5a":"Se lanzan ",
  "yrules.5b":"dados de verdad",
  "yrules.5c":": introduce los 5 valores, elige la casilla y la aplicación cuenta."
}
});
