/* Textes du cornhole. */
ajouterTextes({
fr:{
  "games.cornhole.sub":"Simple, double et tournois",
  "game.bags":"{n} sacs par équipe",
  "game.hole":"Trou",
  "game.hole.pts":"3 pts",
  "game.board":"Planche",
  "game.board.pts":"1 pt",
  "game.none":"Aucun sac compté",
  "game.tie":"Manche nulle — 0 point",
  "game.add.hole":"Ajouter un sac dans le trou",
  "game.rm.hole":"Retirer un sac dans le trou",
  "game.add.board":"Ajouter un sac sur la planche",
  "game.rm.board":"Retirer un sac sur la planche",
  "over.holes":"Sacs dans le trou",
  "over.board":"Sacs sur la planche",
  "rules.count":"Comptage",
  "rules.hole":"Sac dans le trou",
  "rules.board":"Sac sur la planche",
  "rules.flow":"Déroulé d'une manche",
  "rules.1a":"Chaque équipe lance ",
  "rules.1b":"4 sacs",
  "rules.1c":" par manche — en double, 2 sacs par joueur.",
  "rules.2a":"Seule la ",
  "rules.2b":"différence",
  "rules.2c":" est marquée : 5 points contre 3 rapportent 2 points, l'autre équipe n'en marque aucun.",
  "rules.3a":"L'équipe qui a marqué ",
  "rules.3b":"lance en premier",
  "rules.3c":" à la manche suivante. La toute première est tirée au sort.",
  "rules.4a":"La partie s'arrête dès qu'une équipe ",
  "rules.4b":"atteint le score visé",
  "rules.4c":"."
},
en:{
  "games.cornhole.sub":"Singles, doubles and tournaments",
  "game.bags":"{n} bags per team",
  "game.hole":"Hole",
  "game.hole.pts":"3 pts",
  "game.board":"Board",
  "game.board.pts":"1 pt",
  "game.none":"No bags counted",
  "game.tie":"Tied frame — no points",
  "game.add.hole":"Add a bag in the hole",
  "game.rm.hole":"Remove a bag in the hole",
  "game.add.board":"Add a bag on the board",
  "game.rm.board":"Remove a bag on the board",
  "over.holes":"Bags in the hole",
  "over.board":"Bags on the board",
  "rules.count":"Scoring",
  "rules.hole":"Bag in the hole",
  "rules.board":"Bag on the board",
  "rules.flow":"How a frame goes",
  "rules.1a":"Each team throws ",
  "rules.1b":"4 bags",
  "rules.1c":" per frame — in doubles, 2 bags each.",
  "rules.2a":"Only the ",
  "rules.2b":"difference",
  "rules.2c":" counts: 5 points against 3 scores 2, and the other team scores nothing.",
  "rules.3a":"Whoever scored ",
  "rules.3b":"throws first",
  "rules.3c":" in the next frame. The very first is decided by a toss.",
  "rules.4a":"The game ends as soon as a team ",
  "rules.4b":"reaches the target score",
  "rules.4c":"."
},
es:{
  "games.cornhole.sub":"Individual, parejas y torneos",
  "game.bags":"{n} bolsas por equipo",
  "game.hole":"Hoyo",
  "game.hole.pts":"3 pts",
  "game.board":"Tabla",
  "game.board.pts":"1 pt",
  "game.none":"Ninguna bolsa contada",
  "game.tie":"Ronda empatada — sin puntos",
  "game.add.hole":"Añadir una bolsa en el hoyo",
  "game.rm.hole":"Quitar una bolsa del hoyo",
  "game.add.board":"Añadir una bolsa en la tabla",
  "game.rm.board":"Quitar una bolsa de la tabla",
  "over.holes":"Bolsas en el hoyo",
  "over.board":"Bolsas en la tabla",
  "rules.count":"Puntuación",
  "rules.hole":"Bolsa en el hoyo",
  "rules.board":"Bolsa en la tabla",
  "rules.flow":"Cómo transcurre una ronda",
  "rules.1a":"Cada equipo lanza ",
  "rules.1b":"4 bolsas",
  "rules.1c":" por ronda; en parejas, 2 bolsas cada uno.",
  "rules.2a":"Solo cuenta la ",
  "rules.2b":"diferencia",
  "rules.2c":": 5 puntos contra 3 anotan 2, y el otro equipo no anota nada.",
  "rules.3a":"Quien haya anotado ",
  "rules.3b":"lanza primero",
  "rules.3c":" en la ronda siguiente. La primera se decide por sorteo.",
  "rules.4a":"La partida termina en cuanto un equipo ",
  "rules.4b":"alcanza los puntos fijados",
  "rules.4c":"."
}
});
