/* Textes de la pétanque.

   Les clés suivies de @petanque remplacent les clés communes tant que la
   pétanque est le jeu courant : on y dit « mène » et non « manche », et
   c'est l'équipe qui a la main qui lance le but. */
ajouterTextes({
fr:{
  "pe.name":"Pétanque",
  "pe.tile.sub":"Tête-à-tête, doublette, triplette",
  "pe.console":"{n} boules par équipe",
  "pe.perboule":"1 pt par boule",
  "pe.void":"Mène nulle",
  "pe.add":"Ajouter un point",
  "pe.rm":"Retirer un point",
  "pe.chrono":"Chrono",
  "pe.chrono.go":"Lancer",
  "pe.chrono.stop":"Arrêter",
  "pe.chrono.again":"Relancer",
  "pe.chrono.out":"Temps écoulé",
  "mode.triple":"Triple", "mode.triple.sub":"3 v 3",

  "mode.single@petanque":"Tête-à-tête", "mode.single.sub@petanque":"1 v 1",
  "mode.double@petanque":"Doublette", "mode.double.sub@petanque":"2 v 2",
  "mode.triple@petanque":"Triplette", "mode.triple.sub@petanque":"3 v 3",
  "game.frame@petanque":"Mène",
  "game.first@petanque":"Lance le but",
  "toss.who@petanque":"Qui lance le but",
  "toss.result@petanque":"{name} lance le but",
  "sheet.frame@petanque":"Mène",
  "sheet.empty@petanque":"Aucune mène jouée pour l'instant.",
  "sheet.hint@petanque":"Touchez une mène pour corriger son décompte. Le score est recalculé sur toute la partie.",
  "sheet.undo@petanque":"Annuler la dernière mène",
  "sheet.fix.aria@petanque":"Corriger la mène {n}",
  "edit.title@petanque":"Correction · mène {n}",
  "edit.delete@petanque":"Supprimer cette mène",
  "over.done@petanque":"Partie terminée en {n} mène", "over.done_p@petanque":"Partie terminée en {n} mènes",
  "over.nframes@petanque":"{n} mène", "over.nframes_p@petanque":"{n} mènes",
  "over.best@petanque":"Meilleure mène",
  "over.won@petanque":"Mènes gagnées",
  "over.avg@petanque":"Moyenne par mène",
  "over.void@petanque":"Mènes nulles",
  "over.chart.aria@petanque":"Progression des points : {a} {sa}, {b} {sb}, en {n} mène",
  "over.chart.aria_p@petanque":"Progression des points : {a} {sa}, {b} {sb}, en {n} mènes",
  "share.game@petanque":"{a} {sa} – {sb} {b} · {n} mène · ScoreToss",
  "share.game_p@petanque":"{a} {sa} – {sb} {b} · {n} mènes · ScoreToss",

  "pe.r.count":"Comptage",
  "pe.r.pt":"point par boule mieux placée que la meilleure adverse",
  "pe.r.win":"points pour gagner, 11 en poules et cadrages",

  "pe.r.materiel":"Matériel et terrain",
  "pe.r.materiel.1":"Boules en *métal, creuses*, de 7,05 à 8 cm de diamètre et de 650 à 800 g, homologuées FIPJP, marque et poids gravés. Jamais plombées, sablées ni recuites.",
  "pe.r.materiel.2":"But en *bois ou en synthétique* homologué : 30 mm de diamètre (± 1 mm), 10 à 18 g, qu'un aimant ne soulève pas.",
  "pe.r.materiel.3":"Terrain *libre* : toutes surfaces. Terrain *tracé* : 15 × 4 m au moins en championnat, 12 × 3 m par dérogation ; ses lignes de fond sont des lignes de perte.",

  "pe.r.equipes":"Équipes et début de partie",
  "pe.r.equipes.1":"Triplette, *2 boules* par joueur ; doublette et tête-à-tête, *3 boules* par joueur. Aucune autre formule.",
  "pe.r.equipes.2":"Un *tirage au sort* désigne l'équipe qui choisit le terrain, s'il n'est pas imposé, et lance le but.",
  "pe.r.equipes.3":"Cercle tracé de *35 à 50 cm* de diamètre, ou rigide de 50 cm, à plus d'1 m de tout obstacle et à 1,50 m d'un autre cercle ou d'un autre but.",
  "pe.r.equipes.4":"Les pieds restent *entièrement dans le cercle*, sans mordre dessus ni décoller, jusqu'à ce que la boule touche le sol.",

  "pe.r.but":"Lancer du but",
  "pe.r.but.1":"But valable à *6 à 10 m* du cercle, à 50 cm au moins de tout obstacle, et visible du joueur debout dans le cercle.",
  "pe.r.but.2":"*Un seul essai* : manqué, l'adversaire place le but, mais l'équipe qui l'a manqué joue la première boule.",
  "pe.r.but.3":"À la mène suivante, le cercle est tracé *autour du but* de la mène précédente.",
  "pe.r.but.4":"Le but devient *nul* en terrain interdit, invisible du cercle, à plus de 20 m ou moins de 3 m, ou introuvable après cinq minutes.",
  "pe.r.but.5":"But nul : s'il reste des boules aux deux équipes, *la mène est nulle* ; à une seule, elle marque *autant de points que de boules restantes*.",

  "pe.r.mene":"La mène",
  "pe.r.mene.1":"L'équipe qui a lancé le but joue la première boule ; ensuite, *joue l'équipe qui n'a pas le point*.",
  "pe.r.mene.2":"*Une minute* pour jouer chaque boule, comme pour lancer le but.",
  "pe.r.mene.3":"Une boule qui sort en *terrain interdit* est nulle et retirée du jeu.",
  "pe.r.mene.4":"Boule ou but déplacés par le vent, un spectateur, un animal : *remis en place* s'ils étaient marqués. Déplacés par une boule jouée : ils restent.",
  "pe.r.mene.5":"Boule arrêtée par un partenaire : *nulle*. Pointée et arrêtée par un adversaire : rejouée ou laissée, au choix. L'arrêter exprès : *disqualification*.",

  "pe.r.points":"Points et fin de partie",
  "pe.r.points.1":"Seule l'équipe la plus proche marque : *1 point par boule* mieux placée que la meilleure adverse.",
  "pe.r.points.2":"On mesure avec un *instrument adapté*, jamais au pied : le dernier à avoir joué, puis l'adversaire s'il le veut. Boules et obstacles gênants s'écartent, une fois marqués.",
  "pe.r.points.3":"Boules *à égale distance* : l'équipe qui a joué la dernière rejoue, puis l'autre. Sans boule de part et d'autre, *la mène est nulle*.",
  "pe.r.points.4":"Partie en *13 points*, en *11* dans les poules et les cadrages.",

  "pe.r.discipline":"Discipline",
  "pe.r.discipline.1":"Interdit : *modifier le terrain*, seul le trou laissé par une boule pouvant être bouché ; jouer une boule *sans l'avoir nettoyée* ; lancer une boule d'essai.",
  "pe.r.discipline.2":"*Silence* pendant qu'un joueur joue : les adversaires se tiennent sur le côté, à 2 m au moins, derrière lui ou au-delà du but.",
  "pe.r.discipline.3":"Sanctions de l'arbitre : *carton jaune*, l'avertissement ; *orange*, boule annulée ; *rouge*, exclusion pour la partie ; puis disqualification de l'équipe, des deux en cas d'entente.",
  "pe.r.discipline.4":"Temps dépassé : *carton jaune à toute l'équipe*. Un joueur déjà averti perd une boule."
},
en:{
  "pe.name":"Pétanque",
  "pe.tile.sub":"Singles, doubles, triples",
  "pe.console":"{n} boules per team",
  "pe.perboule":"1 pt per boule",
  "pe.void":"Void end",
  "pe.add":"Add a point",
  "pe.rm":"Remove a point",
  "pe.chrono":"Timer",
  "pe.chrono.go":"Start",
  "pe.chrono.stop":"Stop",
  "pe.chrono.again":"Restart",
  "pe.chrono.out":"Time's up",
  "mode.triple":"Triples", "mode.triple.sub":"3 v 3",

  "mode.single@petanque":"Singles", "mode.single.sub@petanque":"1 v 1",
  "mode.double@petanque":"Doubles", "mode.double.sub@petanque":"2 v 2",
  "mode.triple@petanque":"Triples", "mode.triple.sub@petanque":"3 v 3",
  "game.frame@petanque":"End",
  "game.first@petanque":"Throws the jack",
  "toss.who@petanque":"Who throws the jack",
  "toss.result@petanque":"{name} throws the jack",
  "sheet.frame@petanque":"End",
  "sheet.empty@petanque":"No ends played yet.",
  "sheet.hint@petanque":"Tap an end to correct its count. The score is recalculated across the whole game.",
  "sheet.undo@petanque":"Undo the last end",
  "sheet.fix.aria@petanque":"Correct end {n}",
  "edit.title@petanque":"Correction · end {n}",
  "edit.delete@petanque":"Delete this end",
  "over.done@petanque":"Game finished in {n} end", "over.done_p@petanque":"Game finished in {n} ends",
  "over.nframes@petanque":"{n} end", "over.nframes_p@petanque":"{n} ends",
  "over.best@petanque":"Best end",
  "over.won@petanque":"Ends won",
  "over.avg@petanque":"Average per end",
  "over.void@petanque":"Void ends",
  "over.chart.aria@petanque":"Score progression: {a} {sa}, {b} {sb}, over {n} end",
  "over.chart.aria_p@petanque":"Score progression: {a} {sa}, {b} {sb}, over {n} ends",
  "share.game@petanque":"{a} {sa} – {sb} {b} · {n} end · ScoreToss",
  "share.game_p@petanque":"{a} {sa} – {sb} {b} · {n} ends · ScoreToss",

  "pe.r.count":"Scoring",
  "pe.r.pt":"point per boule closer than the opponents' best",
  "pe.r.win":"points to win, 11 in pools and play-offs",

  "pe.r.materiel":"Equipment and ground",
  "pe.r.materiel.1":"Boules made of *hollow metal*, 7.05 to 8 cm across and 650 to 800 g, FIPJP-approved, with maker and weight engraved. Never weighted, filled or re-tempered.",
  "pe.r.materiel.2":"Jack in approved *wood or synthetic*: 30 mm across (± 1 mm), 10 to 18 g, and not picked up by a magnet.",
  "pe.r.materiel.3":"*Open* ground: any surface. *Marked* terrain: at least 15 × 4 m in championships, 12 × 3 m by exemption; its end lines are dead-ball lines.",

  "pe.r.equipes":"Teams and start of play",
  "pe.r.equipes.1":"Triples, *2 boules* each; doubles and singles, *3 boules* each. No other format.",
  "pe.r.equipes.2":"A *toss* decides which team picks the terrain, if none is assigned, and throws the jack.",
  "pe.r.equipes.3":"Drawn circle *35 to 50 cm* across, or a rigid 50 cm one, more than 1 m from any obstacle and 1.50 m from another circle or jack.",
  "pe.r.equipes.4":"Feet stay *wholly inside the circle*, not on the line nor lifted, until the boule touches the ground.",

  "pe.r.but":"Throwing the jack",
  "pe.r.but.1":"The jack is valid *6 to 10 m* from the circle, at least 50 cm from any obstacle, and visible to the player standing in the circle.",
  "pe.r.but.2":"*One attempt only*: if it fails, the opponents place the jack, but the team that failed plays the first boule.",
  "pe.r.but.3":"On the next end, the circle is drawn *around the jack's* last position.",
  "pe.r.but.4":"The jack becomes *dead* in out-of-bounds ground, out of sight from the circle, beyond 20 m or within 3 m, or lost for five minutes.",
  "pe.r.but.5":"Dead jack: if both teams still hold boules, *the end is void*; if only one does, it scores *one point per boule left*.",

  "pe.r.mene":"The end",
  "pe.r.mene.1":"The team that threw the jack plays the first boule; after that, *the team without the point plays*.",
  "pe.r.mene.2":"*One minute* to play each boule, and to throw the jack.",
  "pe.r.mene.3":"A boule that goes into *out-of-bounds* ground is dead and removed.",
  "pe.r.mene.4":"A boule or jack moved by wind, a spectator or an animal is *put back* if it was marked. Moved by a played boule, it stays.",
  "pe.r.mene.5":"A boule stopped by a teammate is *dead*. A pointed boule stopped by an opponent may be replayed or left. Stopping one on purpose: *disqualification*.",

  "pe.r.points":"Points and end of the game",
  "pe.r.points.1":"Only the closest team scores: *1 point per boule* closer than the opponents' best.",
  "pe.r.points.2":"Measure with a *proper tool*, never with feet: the last player to play, then the opponents if they wish. Boules and obstacles in the way may be moved once marked.",
  "pe.r.points.3":"Boules *equally close*: the team that played last plays again, then the other. If neither has boules left, *the end is void*.",
  "pe.r.points.4":"Games to *13 points*, to *11* in pools and play-offs.",

  "pe.r.discipline":"Discipline",
  "pe.r.discipline.1":"Forbidden: *altering the ground*, except filling a hole left by a boule; playing a boule *without cleaning it*; throwing a practice boule.",
  "pe.r.discipline.2":"*Silence* while a player plays: opponents stand to the side, at least 2 m away, behind the player or beyond the jack.",
  "pe.r.discipline.3":"Umpire's sanctions: *yellow card*, the warning; *orange*, boule cancelled; *red*, sent off for the game; then team disqualification, both teams in case of collusion.",
  "pe.r.discipline.4":"Time exceeded: *yellow card to the whole team*. A player already warned loses a boule."
},
es:{
  "pe.name":"Petanca",
  "pe.tile.sub":"Individual, dupletas, tripletas",
  "pe.console":"{n} bolas por equipo",
  "pe.perboule":"1 pt por bola",
  "pe.void":"Jugada nula",
  "pe.add":"Sumar un punto",
  "pe.rm":"Quitar un punto",
  "pe.chrono":"Crono",
  "pe.chrono.go":"Iniciar",
  "pe.chrono.stop":"Parar",
  "pe.chrono.again":"Reiniciar",
  "pe.chrono.out":"Tiempo agotado",
  "mode.triple":"Tripletas", "mode.triple.sub":"3 v 3",

  "mode.single@petanque":"Individual", "mode.single.sub@petanque":"1 v 1",
  "mode.double@petanque":"Dupletas", "mode.double.sub@petanque":"2 v 2",
  "mode.triple@petanque":"Tripletas", "mode.triple.sub@petanque":"3 v 3",
  "game.frame@petanque":"Jugada",
  "game.first@petanque":"Lanza el boliche",
  "toss.who@petanque":"Quién lanza el boliche",
  "toss.result@petanque":"{name} lanza el boliche",
  "sheet.frame@petanque":"Jugada",
  "sheet.empty@petanque":"Todavía no se ha jugado ninguna jugada.",
  "sheet.hint@petanque":"Toca una jugada para corregir su recuento. La puntuación se recalcula en toda la partida.",
  "sheet.undo@petanque":"Deshacer la última jugada",
  "sheet.fix.aria@petanque":"Corregir la jugada {n}",
  "edit.title@petanque":"Corrección · jugada {n}",
  "edit.delete@petanque":"Eliminar esta jugada",
  "over.done@petanque":"Partida terminada en {n} jugada", "over.done_p@petanque":"Partida terminada en {n} jugadas",
  "over.nframes@petanque":"{n} jugada", "over.nframes_p@petanque":"{n} jugadas",
  "over.best@petanque":"Mejor jugada",
  "over.won@petanque":"Jugadas ganadas",
  "over.avg@petanque":"Promedio por jugada",
  "over.void@petanque":"Jugadas nulas",
  "over.chart.aria@petanque":"Progresión de puntos: {a} {sa}, {b} {sb}, en {n} jugada",
  "over.chart.aria_p@petanque":"Progresión de puntos: {a} {sa}, {b} {sb}, en {n} jugadas",
  "share.game@petanque":"{a} {sa} – {sb} {b} · {n} jugada · ScoreToss",
  "share.game_p@petanque":"{a} {sa} – {sb} {b} · {n} jugadas · ScoreToss",

  "pe.r.count":"Puntuación",
  "pe.r.pt":"punto por bola mejor colocada que la mejor rival",
  "pe.r.win":"puntos para ganar, 11 en liguillas y repescas",

  "pe.r.materiel":"Material y terreno",
  "pe.r.materiel.1":"Bolas de *metal, huecas*, de 7,05 a 8 cm de diámetro y de 650 a 800 g, homologadas por la FIPJP, con marca y peso grabados. Nunca lastradas, rellenas ni recocidas.",
  "pe.r.materiel.2":"Boliche de *madera o sintético* homologado: 30 mm de diámetro (± 1 mm), de 10 a 18 g, y que un imán no levante.",
  "pe.r.materiel.3":"Terreno *libre*: cualquier superficie. Terreno *marcado*: 15 × 4 m como mínimo en campeonatos, 12 × 3 m por excepción; sus líneas de fondo son líneas de pérdida.",

  "pe.r.equipes":"Equipos e inicio de la partida",
  "pe.r.equipes.1":"Tripletas, *2 bolas* por jugador; dupletas e individual, *3 bolas* por jugador. Ninguna otra fórmula.",
  "pe.r.equipes.2":"Un *sorteo* decide qué equipo elige el terreno, si no está asignado, y lanza el boliche.",
  "pe.r.equipes.3":"Círculo trazado de *35 a 50 cm* de diámetro, o rígido de 50 cm, a más de 1 m de cualquier obstáculo y a 1,50 m de otro círculo o boliche.",
  "pe.r.equipes.4":"Los pies quedan *por completo dentro del círculo*, sin pisar la línea ni despegarse, hasta que la bola toque el suelo.",

  "pe.r.but":"Lanzamiento del boliche",
  "pe.r.but.1":"El boliche es válido a *6 a 10 m* del círculo, a 50 cm como mínimo de cualquier obstáculo, y visible desde el círculo con el jugador de pie.",
  "pe.r.but.2":"*Un solo intento*: si falla, el rival coloca el boliche, pero el equipo que falló juega la primera bola.",
  "pe.r.but.3":"En la jugada siguiente, el círculo se traza *alrededor del boliche* de la jugada anterior.",
  "pe.r.but.4":"El boliche es *nulo* en terreno prohibido, invisible desde el círculo, a más de 20 m o menos de 3 m, o perdido tras cinco minutos.",
  "pe.r.but.5":"Boliche nulo: si a ambos equipos les quedan bolas, *la jugada es nula*; si solo a uno, este suma *tantos puntos como bolas le quedan*.",

  "pe.r.mene":"La jugada",
  "pe.r.mene.1":"El equipo que lanzó el boliche juega la primera bola; después, *juega el equipo que no tiene el punto*.",
  "pe.r.mene.2":"*Un minuto* para jugar cada bola, igual que para lanzar el boliche.",
  "pe.r.mene.3":"Una bola que sale a *terreno prohibido* es nula y se retira.",
  "pe.r.mene.4":"Bola o boliche movidos por el viento, un espectador o un animal: *se reponen* si estaban marcados. Movidos por una bola jugada: se quedan.",
  "pe.r.mene.5":"Bola detenida por un compañero: *nula*. Arrimada y detenida por un rival: se repite o se deja, a elección. Detenerla a propósito: *descalificación*.",

  "pe.r.points":"Puntos y final de la partida",
  "pe.r.points.1":"Solo puntúa el equipo más cercano: *1 punto por bola* mejor colocada que la mejor rival.",
  "pe.r.points.2":"Se mide con un *instrumento adecuado*, nunca con el pie: el último en jugar, luego el rival si quiere. Bolas y obstáculos que estorben se apartan, una vez marcados.",
  "pe.r.points.3":"Bolas *a igual distancia*: vuelve a jugar el equipo que jugó la última, luego el otro. Sin bolas en ningún lado, *la jugada es nula*.",
  "pe.r.points.4":"Partidas a *13 puntos*, a *11* en liguillas y repescas.",

  "pe.r.discipline":"Disciplina",
  "pe.r.discipline.1":"Prohibido: *modificar el terreno*, salvo tapar el hoyo que dejó una bola; jugar una bola *sin limpiarla*; lanzar una bola de prueba.",
  "pe.r.discipline.2":"*Silencio* mientras alguien juega: los rivales se colocan a un lado, a 2 m como mínimo, detrás del jugador o más allá del boliche.",
  "pe.r.discipline.3":"Sanciones del árbitro: *tarjeta amarilla*, la advertencia; *naranja*, bola anulada; *roja*, expulsión para la partida; después, descalificación del equipo, de ambos si hay connivencia.",
  "pe.r.discipline.4":"Tiempo superado: *amarilla a todo el equipo*. Un jugador ya advertido pierde una bola."
}
});
