/* Textes du Tossit. Les noms des bonus sont ceux du jeu, gardés tels quels. */
ajouterTextes({
fr:{
  "ti.name":"Tossit",
  "ti.tile.sub":"Au plus près du jack, en 13",
  "ti.mode.solo":"Individuel", "ti.mode.solo.sub":"Chacun pour soi",
  "ti.mode.team":"Équipes", "ti.mode.team.sub":"Score commun",
  "ti.darts":"Fléchettes chacun",
  "ti.darts.hint":"Le joueur 1 lance le jack en premier : le plus âgé, dit la règle.",
  "ti.players":"Joueurs", "ti.teams":"Équipes", "ti.per":"Joueurs par équipe",
  "ti.note":"{n} joueurs · premier à 13", "ti.note.team":"{n} équipes · premier à 13",
  "ti.playern":"Joueur {n}", "ti.teamn":"Équipe {n}",
  "ti.player.aria":"Nom du joueur {n}", "ti.team.aria":"Nom de l'équipe {n}",
  "ti.mate.aria":"Joueur {j} de l'équipe {n}", "ti.color.aria":"Couleur du joueur {n}",
  "ti.type.gain":"Manche", "ti.type.quake":"Jackquake", "ti.type.jackoff":"Jackoff", "ti.type.jack0":"Jack-0",
  "ti.f":"Fléchettes collées", "ti.f.n":"{n} fl.",
  "ti.b.kiss":"Kiss", "ti.b.french":"French Kiss", "ti.b.jackiss":"Jackiss",
  "ti.b.saut":"Par-dessus", "ti.b.jackover":"Jackover",
  "ti.lancees":"Fléchettes lancées", "ti.lancees.n":"{n} lancées",
  "ti.aide.quake":"Le jack est tombé au moment où sa fléchette collait : +1, plus 1 par fléchette lancée. La manche s'arrête.",
  "ti.aide.jackoff":"Le jack est tombé : touchez le joueur le plus proche avant la chute. +1, la manche s'arrête.",
  "ti.aide.jack0":"Aucune fléchette n'a collé : +1 pour {name}, qui a lancé le jack.",
  "ti.moins":"{what} : un de moins", "ti.plus":"{what} : un de plus",
  "ti.choose":"Touchez le gagnant de la manche",
  "ti.jack.who":"{name} lance le jack",
  "ti.jack":"Jack",
  "ti.win.jackover":"{name} gagne par Jackover",
  "ti.effet.victoire":"Victoire", "ti.effet.jackover":"Jackover : victoire immédiate",
  "ti.effet.saut":"Les autres repartent de zéro", "ti.effet.fin":"La manche s'arrête",
  "ti.effet.reste":"Encore {n} pour gagner",
  "ti.done":"Partie terminée",
  "ti.col.who":"Joueur", "ti.col.how":"Comment",
  "ti.col.won":"Manches", "ti.col.bonus":"Bonus",
  "ti.sheet.hint":"Touchez une manche pour la corriger : gagnant, fléchettes ou bonus. La partie est recalculée.",
  "ti.points":"points",
  "ti.note.jackover":"Victoire par Jackover : une fléchette collée sur le jack.",
  "ti.rank":"Classement",
  "tirules.count":"Comptage",
  "tirules.pt":"Par fléchette collée, pour le gagnant de la manche seulement",
  "tirules.bonus":"Bonus du gagnant",
  "tirules.kiss":"Kiss · la fléchette touche une autre fléchette collée",
  "tirules.french":"French Kiss · elle s'enroule autour d'une autre par la tige",
  "tirules.jackiss":"Jackiss · elle touche le jack",
  "tirules.saut":"Sautez par-dessus · collée sur une autre fléchette ; les adversaires retombent à 0",
  "tirules.jackover":"Jackover · collée sur le jack : victoire immédiate",
  "tirules.fins":"Fins de manche spéciales",
  "tirules.quake":"Jackquake · le jack tombe quand sa fléchette colle : +1 par fléchette lancée en plus",
  "tirules.jackoff":"Jackoff · le jack tombe : +1 au plus proche avant la chute",
  "tirules.jack0":"Jack-0 · aucune fléchette n'a collé : +1 à celui qui a lancé le jack",
  "tirules.flow":"Déroulé",
  "tirules.1a":"Le plus âgé lance d'abord ",
  "tirules.1b":"la fléchette noire, le jack",
  "tirules.1c":" ; s'il la rate, les suivants essaient à tour de rôle.",
  "tirules.2a":"Puis chacun lance ",
  "tirules.2b":"à tour de rôle",
  "tirules.2c":" jusqu'à la dernière fléchette. Une fléchette qui ne colle pas n'est pas relancée.",
  "tirules.3a":"Le plus proche du jack ",
  "tirules.3b":"gagne la manche",
  "tirules.3c":" : un point par fléchette qu'il a collée, et les autres ne marquent rien.",
  "tirules.4a":"Les bonus ne comptent que pour le gagnant, et ",
  "tirules.4b":"la fléchette doit tenir 3 secondes",
  "tirules.4c":".",
  "tirules.5a":"Le gagnant lance le jack de la manche suivante. ",
  "tirules.5b":"13 points",
  "tirules.5c":" gagnent la partie."
},
en:{
  "ti.name":"Tossit",
  "ti.tile.sub":"Closest to the jack, to 13",
  "ti.mode.solo":"Individual", "ti.mode.solo.sub":"Each on their own",
  "ti.mode.team":"Teams", "ti.mode.team.sub":"Shared score",
  "ti.darts":"Darts each",
  "ti.darts.hint":"Player 1 throws the jack first: the oldest, says the rule.",
  "ti.players":"Players", "ti.teams":"Teams", "ti.per":"Players per team",
  "ti.note":"{n} players · first to 13", "ti.note.team":"{n} teams · first to 13",
  "ti.playern":"Player {n}", "ti.teamn":"Team {n}",
  "ti.player.aria":"Name of player {n}", "ti.team.aria":"Name of team {n}",
  "ti.mate.aria":"Player {j} of team {n}", "ti.color.aria":"Colour of player {n}",
  "ti.type.gain":"Round", "ti.type.quake":"Jackquake", "ti.type.jackoff":"Jackoff", "ti.type.jack0":"Jack-0",
  "ti.f":"Darts stuck", "ti.f.n":"{n} darts",
  "ti.b.kiss":"Kiss", "ti.b.french":"French Kiss", "ti.b.jackiss":"Jackiss",
  "ti.b.saut":"Jumpover", "ti.b.jackover":"Jackover",
  "ti.lancees":"Darts thrown", "ti.lancees.n":"{n} thrown",
  "ti.aide.quake":"The jack fell just as their dart stuck: +1, plus 1 per dart thrown. The round ends.",
  "ti.aide.jackoff":"The jack fell: tap the player who was closest before it fell. +1, the round ends.",
  "ti.aide.jack0":"No dart stuck: +1 for {name}, who threw the jack.",
  "ti.moins":"{what}: one fewer", "ti.plus":"{what}: one more",
  "ti.choose":"Tap the winner of the round",
  "ti.jack.who":"{name} throws the jack",
  "ti.jack":"Jack",
  "ti.win.jackover":"{name} wins with a Jackover",
  "ti.effet.victoire":"Win", "ti.effet.jackover":"Jackover: instant win",
  "ti.effet.saut":"Everyone else drops to zero", "ti.effet.fin":"The round ends",
  "ti.effet.reste":"{n} more to win",
  "ti.done":"Game over",
  "ti.col.who":"Player", "ti.col.how":"How",
  "ti.col.won":"Rounds", "ti.col.bonus":"Bonus",
  "ti.sheet.hint":"Tap a round to correct it: winner, darts or bonuses. The game is recalculated.",
  "ti.points":"points",
  "ti.note.jackover":"Won with a Jackover: a dart stuck on the jack.",
  "ti.rank":"Standings",
  "tirules.count":"Scoring",
  "tirules.pt":"Per dart stuck, for the round winner only",
  "tirules.bonus":"Winner's bonuses",
  "tirules.kiss":"Kiss · the dart touches another stuck dart",
  "tirules.french":"French Kiss · it wraps around another one by the shaft",
  "tirules.jackiss":"Jackiss · it touches the jack",
  "tirules.saut":"Jumpover · stuck on top of another dart; opponents drop to 0",
  "tirules.jackover":"Jackover · stuck on top of the jack: instant win",
  "tirules.fins":"Special round endings",
  "tirules.quake":"Jackquake · the jack falls as their dart sticks: plus 1 per dart thrown",
  "tirules.jackoff":"Jackoff · the jack falls: +1 to whoever was closest before",
  "tirules.jack0":"Jack-0 · no dart stuck: +1 to whoever threw the jack",
  "tirules.flow":"How it goes",
  "tirules.1a":"The oldest player first throws ",
  "tirules.1b":"the black dart, the jack",
  "tirules.1c":"; if it misses, the others try in turn.",
  "tirules.2a":"Then everyone throws ",
  "tirules.2b":"in turn",
  "tirules.2c":" until the last dart. A dart that doesn't stick is not thrown again.",
  "tirules.3a":"The player closest to the jack ",
  "tirules.3b":"wins the round",
  "tirules.3c":": one point per dart they stuck, and nobody else scores.",
  "tirules.4a":"Bonuses only count for the winner, and ",
  "tirules.4b":"the dart must hold for 3 seconds",
  "tirules.4c":".",
  "tirules.5a":"The winner throws the jack in the next round. ",
  "tirules.5b":"13 points",
  "tirules.5c":" win the game."
},
es:{
  "ti.name":"Tossit",
  "ti.tile.sub":"Lo más cerca del jack, a 13",
  "ti.mode.solo":"Individual", "ti.mode.solo.sub":"Cada uno por su cuenta",
  "ti.mode.team":"Equipos", "ti.mode.team.sub":"Puntuación común",
  "ti.darts":"Dardos por jugador",
  "ti.darts.hint":"El jugador 1 lanza el jack primero: el mayor, dice la regla.",
  "ti.players":"Jugadores", "ti.teams":"Equipos", "ti.per":"Jugadores por equipo",
  "ti.note":"{n} jugadores · el primero a 13", "ti.note.team":"{n} equipos · el primero a 13",
  "ti.playern":"Jugador {n}", "ti.teamn":"Equipo {n}",
  "ti.player.aria":"Nombre del jugador {n}", "ti.team.aria":"Nombre del equipo {n}",
  "ti.mate.aria":"Jugador {j} del equipo {n}", "ti.color.aria":"Color del jugador {n}",
  "ti.type.gain":"Ronda", "ti.type.quake":"Jackquake", "ti.type.jackoff":"Jackoff", "ti.type.jack0":"Jack-0",
  "ti.f":"Dardos pegados", "ti.f.n":"{n} dardos",
  "ti.b.kiss":"Kiss", "ti.b.french":"French Kiss", "ti.b.jackiss":"Jackiss",
  "ti.b.saut":"Por encima", "ti.b.jackover":"Jackover",
  "ti.lancees":"Dardos lanzados", "ti.lancees.n":"{n} lanzados",
  "ti.aide.quake":"El jack cayó justo cuando su dardo se pegaba: +1, más 1 por dardo lanzado. La ronda termina.",
  "ti.aide.jackoff":"El jack cayó: toca al jugador más cercano antes de la caída. +1, la ronda termina.",
  "ti.aide.jack0":"Ningún dardo se pegó: +1 para {name}, que lanzó el jack.",
  "ti.moins":"{what}: uno menos", "ti.plus":"{what}: uno más",
  "ti.choose":"Toca al ganador de la ronda",
  "ti.jack.who":"{name} lanza el jack",
  "ti.jack":"Jack",
  "ti.win.jackover":"{name} gana con un Jackover",
  "ti.effet.victoire":"Victoria", "ti.effet.jackover":"Jackover: victoria inmediata",
  "ti.effet.saut":"Los demás vuelven a cero", "ti.effet.fin":"La ronda termina",
  "ti.effet.reste":"Faltan {n} para ganar",
  "ti.done":"Partida terminada",
  "ti.col.who":"Jugador", "ti.col.how":"Cómo",
  "ti.col.won":"Rondas", "ti.col.bonus":"Bonus",
  "ti.sheet.hint":"Toca una ronda para corregirla: ganador, dardos o bonus. La partida se recalcula.",
  "ti.points":"puntos",
  "ti.note.jackover":"Victoria con un Jackover: un dardo pegado sobre el jack.",
  "ti.rank":"Clasificación",
  "tirules.count":"Puntuación",
  "tirules.pt":"Por dardo pegado, solo para el ganador de la ronda",
  "tirules.bonus":"Bonus del ganador",
  "tirules.kiss":"Kiss · el dardo toca otro dardo pegado",
  "tirules.french":"French Kiss · se enrolla alrededor de otro por la varilla",
  "tirules.jackiss":"Jackiss · toca el jack",
  "tirules.saut":"Por encima · pegado sobre otro dardo; los rivales vuelven a 0",
  "tirules.jackover":"Jackover · pegado sobre el jack: victoria inmediata",
  "tirules.fins":"Finales de ronda especiales",
  "tirules.quake":"Jackquake · el jack cae cuando su dardo se pega: más 1 por dardo lanzado",
  "tirules.jackoff":"Jackoff · el jack cae: +1 al más cercano antes de la caída",
  "tirules.jack0":"Jack-0 · ningún dardo se pegó: +1 a quien lanzó el jack",
  "tirules.flow":"Desarrollo",
  "tirules.1a":"El mayor lanza primero ",
  "tirules.1b":"el dardo negro, el jack",
  "tirules.1c":"; si falla, los demás lo intentan por turnos.",
  "tirules.2a":"Después cada uno lanza ",
  "tirules.2b":"por turnos",
  "tirules.2c":" hasta el último dardo. Un dardo que no se pega no se vuelve a lanzar.",
  "tirules.3a":"El más cercano al jack ",
  "tirules.3b":"gana la ronda",
  "tirules.3c":": un punto por dardo pegado, y los demás no puntúan.",
  "tirules.4a":"Los bonus solo cuentan para el ganador, y ",
  "tirules.4b":"el dardo debe aguantar 3 segundos",
  "tirules.4c":".",
  "tirules.5a":"El ganador lanza el jack en la ronda siguiente. ",
  "tirules.5b":"13 puntos",
  "tirules.5c":" ganan la partida."
}
});
