/* Textes du mölkky. */
ajouterTextes({
fr:{
  "molkky.name":"Mölkky",
  "games.molkky.sub":"À plusieurs, quilles numérotées",
  "mk.players":"Joueurs",
  "mk.playern":"Joueur {n}",
  "mk.player.aria":"Nom du joueur {n}",
  "mk.color.aria":"Couleur du joueur {n}",
  "mk.note":"{n} joueurs · premier à 50 exactement",
  "mk.turn":"À {name}",
  "mk.miss":"Raté",
  "mk.throw.aria":"{name} marque {n} point",
  "mk.throw.aria_p":"{name} marque {n} points",
  "mk.miss.aria":"{name} manque son lancer",
  "mk.out":"Éliminé",
  "mk.misses":"{n} raté de suite",
  "mk.misses_p":"{n} ratés de suite",
  "mk.back25":"Dépassement — retour à 25",
  "mk.layout":"Placement des quilles",
  "mk.layout.open":"Voir le placement des quilles",
  "mk.layout.hint":"Formation de départ, à 3,50 m de la zone de lancer. Une quille renversée se relève là où elle est tombée, numéro vers les lanceurs — c'est ainsi qu'elles se dispersent.",
  "mk.thrower":"Zone de lancer",
  "mk.undo":"Annuler le dernier lancer",
  "mk.sheet.empty":"Aucun lancer pour l'instant.",
  "mk.sheet.hint":"Touchez un lancer pour le corriger. La partie est recalculée depuis le début.",
  "mk.fix.aria":"Corriger le lancer {n}",
  "mk.edit.title":"Correction · lancer {n}",
  "mk.done":"Partie terminée en {n} lancers",
  "mk.left":"Reste {n}",
  "mk.next":"Ensuite", "mk.encore":"Au moins {n} lancers pour finir",
  "mk.idee":"La quille {n} seule, ou {n} quilles d'un coup", "mk.idee.1":"La quille 1 seule",
  "mk.rank":"Classement final",
  "mrules.title":"Le mölkky",
  "mrules.count":"Comptage",
  "mrules.one":"une seule quille renversée : son numéro, de 1 à 12",
  "mrules.many":"plusieurs quilles renversées : leur nombre",
  "mrules.flow":"Déroulé",
  "mrules.1a":"Le premier à ",
  "mrules.1b":"50 points exactement",
  "mrules.1c":" l'emporte.",
  "mrules.2a":"Dépasser 50 ramène le score à ",
  "mrules.2b":"25",
  "mrules.2c":".",
  "mrules.3a":"",
  "mrules.3b":"Trois lancers manqués",
  "mrules.3c":" de suite éliminent le joueur.",
  "mrules.4a":"Une quille renversée se relève ",
  "mrules.4b":"là où elle est tombée",
  "mrules.4c":", sans être déplacée.",
  "mrules.5a":"On lance à ",
  "mrules.5b":"3,50 m",
  "mrules.5c":", chacun son tour.",
  "mk.pins.one":"1 quille",
  "mk.pins.one.v":"son n°",
  "mk.pins.many.v":"leur nombre",
  "mk.mode.solo":"Individuel",
  "mk.mode.solo.sub":"Chacun pour soi",
  "mk.mode.team":"Équipes",
  "mk.mode.team.sub":"Score commun",
  "mk.per":"Joueurs par équipe",
  "mk.teams":"Équipes",
  "mk.teamn":"Équipe {n}",
  "mk.team.aria":"Nom de l'équipe {n}",
  "mk.mate.aria":"Joueur {j} de l'équipe {n}",
  "mk.note.team":"{n} équipes · premier à 50 exactement",
  "mk.turn.team":"À {team} · {name}"
},
en:{
  "molkky.name":"Mölkky",
  "games.molkky.sub":"Several players, numbered pins",
  "mk.players":"Players",
  "mk.playern":"Player {n}",
  "mk.player.aria":"Name of player {n}",
  "mk.color.aria":"Colour of player {n}",
  "mk.note":"{n} players · first to exactly 50",
  "mk.turn":"{name} to throw",
  "mk.miss":"Miss",
  "mk.throw.aria":"{name} scores {n} point",
  "mk.throw.aria_p":"{name} scores {n} points",
  "mk.miss.aria":"{name} misses",
  "mk.out":"Out",
  "mk.misses":"{n} miss in a row",
  "mk.misses_p":"{n} misses in a row",
  "mk.back25":"Overshot — back to 25",
  "mk.layout":"Pin layout",
  "mk.layout.open":"See the pin layout",
  "mk.layout.hint":"Starting formation, 3.50 m from the throwing line. A pin that falls is stood back up where it landed, number facing the throwers — which is how they spread out.",
  "mk.thrower":"Throwing line",
  "mk.undo":"Undo the last throw",
  "mk.sheet.empty":"No throws yet.",
  "mk.sheet.hint":"Tap a throw to correct it. The game is recalculated from the start.",
  "mk.fix.aria":"Correct throw {n}",
  "mk.edit.title":"Correction · throw {n}",
  "mk.done":"Game finished in {n} throws",
  "mk.left":"{n} to go",
  "mk.next":"Next", "mk.encore":"At least {n} throws to finish",
  "mk.idee":"Pin {n} alone, or any {n} pins at once", "mk.idee.1":"Pin 1 alone",
  "mk.rank":"Final standings",
  "mrules.title":"Mölkky",
  "mrules.count":"Scoring",
  "mrules.one":"one pin down: its number, from 1 to 12",
  "mrules.many":"several pins down: how many",
  "mrules.flow":"How it goes",
  "mrules.1a":"First to ",
  "mrules.1b":"exactly 50 points",
  "mrules.1c":" wins.",
  "mrules.2a":"Going over 50 drops the score back to ",
  "mrules.2b":"25",
  "mrules.2c":".",
  "mrules.3a":"",
  "mrules.3b":"Three missed throws",
  "mrules.3c":" in a row put a player out.",
  "mrules.4a":"A fallen pin is stood back up ",
  "mrules.4b":"where it landed",
  "mrules.4c":", never moved.",
  "mrules.5a":"Throws are made from ",
  "mrules.5b":"3.50 m",
  "mrules.5c":", each in turn.",
  "mk.pins.one":"1 pin",
  "mk.pins.one.v":"its number",
  "mk.pins.many.v":"how many",
  "mk.mode.solo":"Individual",
  "mk.mode.solo.sub":"Each on their own",
  "mk.mode.team":"Teams",
  "mk.mode.team.sub":"Shared score",
  "mk.per":"Players per team",
  "mk.teams":"Teams",
  "mk.teamn":"Team {n}",
  "mk.team.aria":"Name of team {n}",
  "mk.mate.aria":"Player {j} of team {n}",
  "mk.note.team":"{n} teams · first to exactly 50",
  "mk.turn.team":"{team} · {name} to throw"
},
es:{
  "molkky.name":"Mölkky",
  "games.molkky.sub":"Varios jugadores, bolos numerados",
  "mk.players":"Jugadores",
  "mk.playern":"Jugador {n}",
  "mk.player.aria":"Nombre del jugador {n}",
  "mk.color.aria":"Color del jugador {n}",
  "mk.note":"{n} jugadores · el primero en 50 exactos",
  "mk.turn":"Turno de {name}",
  "mk.miss":"Fallo",
  "mk.throw.aria":"{name} anota {n} punto",
  "mk.throw.aria_p":"{name} anota {n} puntos",
  "mk.miss.aria":"{name} falla el lanzamiento",
  "mk.out":"Eliminado",
  "mk.misses":"{n} fallo seguido",
  "mk.misses_p":"{n} fallos seguidos",
  "mk.back25":"Se pasó — vuelta a 25",
  "mk.layout":"Colocación de los bolos",
  "mk.layout.open":"Ver la colocación de los bolos",
  "mk.layout.hint":"Formación inicial, a 3,50 m de la zona de lanzamiento. Un bolo derribado se levanta donde cayó, con el número hacia los lanzadores — así se van dispersando.",
  "mk.thrower":"Zona de lanzamiento",
  "mk.undo":"Deshacer el último lanzamiento",
  "mk.sheet.empty":"Todavía no hay lanzamientos.",
  "mk.sheet.hint":"Toca un lanzamiento para corregirlo. La partida se recalcula desde el principio.",
  "mk.fix.aria":"Corregir el lanzamiento {n}",
  "mk.edit.title":"Corrección · lanzamiento {n}",
  "mk.done":"Partida terminada en {n} lanzamientos",
  "mk.left":"Faltan {n}",
  "mk.next":"Después", "mk.encore":"Al menos {n} tiradas para terminar",
  "mk.idee":"El bolo {n} solo, o {n} bolos de una vez", "mk.idee.1":"El bolo 1 solo",
  "mk.rank":"Clasificación final",
  "mrules.title":"El mölkky",
  "mrules.count":"Puntuación",
  "mrules.one":"un solo bolo derribado: su número, del 1 al 12",
  "mrules.many":"varios bolos derribados: cuántos son",
  "mrules.flow":"Desarrollo",
  "mrules.1a":"Gana el primero en llegar a ",
  "mrules.1b":"50 puntos exactos",
  "mrules.1c":".",
  "mrules.2a":"Pasarse de 50 devuelve la puntuación a ",
  "mrules.2b":"25",
  "mrules.2c":".",
  "mrules.3a":"",
  "mrules.3b":"Tres lanzamientos fallados",
  "mrules.3c":" seguidos eliminan al jugador.",
  "mrules.4a":"Un bolo derribado se levanta ",
  "mrules.4b":"donde cayó",
  "mrules.4c":", sin moverlo.",
  "mrules.5a":"Se lanza desde ",
  "mrules.5b":"3,50 m",
  "mrules.5c":", por turnos.",
  "mk.pins.one":"1 bolo",
  "mk.pins.one.v":"su número",
  "mk.pins.many.v":"cuántos",
  "mk.mode.solo":"Individual",
  "mk.mode.solo.sub":"Cada uno por su cuenta",
  "mk.mode.team":"Equipos",
  "mk.mode.team.sub":"Puntuación común",
  "mk.per":"Jugadores por equipo",
  "mk.teams":"Equipos",
  "mk.teamn":"Equipo {n}",
  "mk.team.aria":"Nombre del equipo {n}",
  "mk.mate.aria":"Jugador {j} del equipo {n}",
  "mk.note.team":"{n} equipos · el primero en 50 exactos",
  "mk.turn.team":"Turno de {team} · {name}"
}
});
